### ISSUE TITLE
Docker tag

### ISSUE THREAD

**Issue by w111a** [FreeTAKTeam/FreeTAKServer-Docker#13]
I first tried to use a docker command including  freetakteam/freetakserver:1.7.5 as described in the readme. The container would not download and checking dockerhub:tags it looks like 1.7.5 is not listed and :dev is the correct tag for 1.7.5.

**Comment by skadakar** [comment]
Readme is written under the assumption that it will be released, currently it's not tested well enough to hand off to people without expecting problems.

**Comment by w111a** [comment]
Understood. Maybe the example command should contain a version/tag that can be pulled from dockerhub. Might avoid some headaches for some people. 

Thanks for maintaining this 👍

**Comment by LargoUsagi** [comment]
@w111a Currently 1.7.5 is on the dev tag.  It needs more testing before being tagged off as a stable release.
