### ISSUE TITLE
Running CLI from within Docker

### ISSUE THREAD

**Issue by hogmo1311** [FreeTAKTeam/FreeTAKServer-Docker#16]
Getting an error when attempting to run the CLI from within Docker. 
The command "docker exec -it fts python3 -m FreeTAKServer.views.CLI" results in an error

  Is the Python module included in the Docker Container/Image?
![image](https://user-images.githubusercontent.com/74543586/117589557-34413a00-b0f8-11eb-8b4a-c55bcf32b433.png)

**Comment by sgofferj** [comment]
@skadakar I think, you are mixing UI and **CLI** here. The [docs](https://freetakteam.github.io/FreeTAKServer-User-Docs/Installation/Docker/CLI/) give this specific command to start the CLI. The command does make sense if you want to start a python submodule inside the context of the docker container. I do have the same problem. I try to get into the CLI with that command and I also get the same error. So either the command is wrong in the docs or the module was not built in the container.
Please reopen.
