### ISSUE TITLE
start-fts.sh fails to log error correctly

### ISSUE THREAD

**Issue by dbussert** [FreeTAKTeam/FreeTAKServer-Docker#3]
![image](https://user-images.githubusercontent.com/2479487/110208607-31a33980-7e56-11eb-8640-b9ebbd87df5a.png)

`/start-fts.sh: line 5: log: command not found`

**Comment by rlex** [comment]
Image version?

**Comment by dbussert** [comment]
`freetakteam/freetakserver:1.2.5` when mounting a data volume that is not owned by the `uid`/`gid` `1000`. That triggers the original error, but the bigger problem is the log message does not work

**Comment by LargoUsagi** [comment]
This is no longer relevant as we are moving towards 1.7.x, closing for now as the entire pattern has changed.
